import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

import 'features/auth/login_screen.dart';
import 'features/auth/pin_screen.dart';
import 'features/dashboard/dashboard_screen.dart';
import 'shared/theme/app_theme.dart';

// Generated by flutter gen-l10n
import 'l10n/app_localizations.dart';

const _storage = FlutterSecureStorage();
const _jwtKey = 'dave_farm_jwt';
const _pinKey = 'dave_farm_pin';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const DaveFarmApp());
}

class DaveFarmApp extends StatelessWidget {
  const DaveFarmApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dave Farm',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: AppLocalizations.supportedLocales,
      home: const _AuthGate(),
    );
  }
}

/// Decides whether to show PIN, Dashboard, or Login on cold start.
class _AuthGate extends StatefulWidget {
  const _AuthGate();

  @override
  State<_AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<_AuthGate> {
  bool _checking = true;
  Widget? _destination;

  @override
  void initState() {
    super.initState();
    _check();
  }

  Future<void> _check() async {
    final jwt = await _storage.read(key: _jwtKey);
    final pin = await _storage.read(key: _pinKey);

    Widget dest;
    if (jwt != null && jwt.isNotEmpty) {
      // JWT found — user is already authenticated
      if (pin != null && pin.isNotEmpty) {
        // Show PIN screen first, then go to dashboard
        dest = PinScreen(
          onUnlocked: () {
            Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (_) => const DashboardScreen()),
            );
          },
        );
      } else {
        dest = const DashboardScreen();
      }
    } else {
      // No JWT — go to login
      dest = const LoginScreen();
    }

    if (mounted) {
      setState(() {
        _destination = dest;
        _checking = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_checking) {
      return const Scaffold(
        backgroundColor: Color(0xFF121212),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.egg_alt_rounded,
                  size: 64, color: Color(0xFF2E7D32)),
              SizedBox(height: 20),
              Text('Dave Farm',
                  style: TextStyle(
                      fontSize: 24,
                      fontWeight: FontWeight.w800,
                      color: Colors.white)),
              SizedBox(height: 8),
              Text('Poultry Management',
                  style: TextStyle(color: Colors.white54)),
              SizedBox(height: 40),
              CircularProgressIndicator(color: Color(0xFF2E7D32)),
            ],
          ),
        ),
      );
    }
    return _destination!;
  }
}
