import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

import 'features/auth/login_screen.dart';
import 'features/auth/pin_screen.dart';
import 'features/dashboard/dashboard_screen.dart';
import 'shared/theme/app_theme.dart';

// Generated by flutter gen-l10n
import 'features/settings/settings_controller.dart';
import 'features/settings/settings_service.dart';

// Generated by flutter gen-l10n
import 'l10n/app_localizations.dart';

const _storage = FlutterSecureStorage();
const _jwtKey = 'dave_farm_jwt';
const _pinKey = 'dave_farm_pin';
const _offlineKey = 'dave_farm_offline';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  final settingsService = SettingsService();
  final settingsController = SettingsController(settingsService);
  await settingsController.loadSettings();

  runApp(DaveFarmApp(settingsController: settingsController));
}

class DaveFarmApp extends StatelessWidget {
  const DaveFarmApp({super.key, required this.settingsController});

  final SettingsController settingsController;

  @override
  Widget build(BuildContext context) {
    return ListenableBuilder(
      listenable: settingsController,
      builder: (context, _) {
        return MaterialApp(
          title: 'Dave Farm',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.light,
          darkTheme: AppTheme.dark,
          themeMode: settingsController.themeMode,
          locale: settingsController.locale,
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            _FallbackMaterialLocalizationsDelegate(),
            _FallbackCupertinoLocalizationsDelegate(),
          ],
          supportedLocales: AppLocalizations.supportedLocales,
          home: _AuthGate(settingsController: settingsController),
        );
      },
    );
  }
}

/// Decides whether to show PIN, Dashboard, or Login on cold start.
class _AuthGate extends StatefulWidget {
  const _AuthGate({required this.settingsController});

  final SettingsController settingsController;

  @override
  State<_AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<_AuthGate> {
  bool _checking = true;
  Widget? _destination;

  @override
  void initState() {
    super.initState();
    _check();
  }

  Future<void> _check() async {
    final jwt = await _storage.read(key: _jwtKey);
    final pin = await _storage.read(key: _pinKey);
    final isOffline = await _storage.read(key: _offlineKey) == 'true';

    Widget dest;
    if ((jwt != null && jwt.isNotEmpty) || isOffline) {
      // JWT found OR user chose persistent offline — user is authenticated
      if (pin != null && pin.isNotEmpty) {
        // Show PIN screen first, then go to dashboard
        dest = PinScreen(
          onUnlocked: () {
            Navigator.of(context).pushReplacement(
              MaterialPageRoute(
                builder: (_) => DashboardScreen(
                  settingsController: widget.settingsController,
                ),
              ),
            );
          },
        );
      } else {
        dest = DashboardScreen(settingsController: widget.settingsController);
      }
    } else {
      // No JWT — go to login
      dest = LoginScreen(settingsController: widget.settingsController);
    }

    if (mounted) {
      setState(() {
        _destination = dest;
        _checking = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_checking) {
      return Scaffold(
        backgroundColor: const Color(0xFF121212),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.egg_alt_rounded,
                  size: 64, color: Color(0xFF2E7D32)),
              const SizedBox(height: 20),
              Text(AppLocalizations.of(context)!.appTitle,
                  style: const TextStyle(
                      fontSize: 24,
                      fontWeight: FontWeight.w800,
                      color: Colors.white)),
              const SizedBox(height: 8),
              Text(AppLocalizations.of(context)!.labelPoultryManagement,
                  style: const TextStyle(color: Colors.white54)),
              const SizedBox(height: 40),
              const CircularProgressIndicator(color: Color(0xFF2E7D32)),
            ],
          ),
        ),
      );
    }
    return _destination!;
  }
}

class _FallbackMaterialLocalizationsDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const _FallbackMaterialLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<MaterialLocalizations> load(Locale locale) async {
    return await GlobalMaterialLocalizations.delegate.load(const Locale('en'));
  }

  @override
  bool shouldReload(_FallbackMaterialLocalizationsDelegate old) => false;
}

class _FallbackCupertinoLocalizationsDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const _FallbackCupertinoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<CupertinoLocalizations> load(Locale locale) async {
    return await GlobalCupertinoLocalizations.delegate.load(const Locale('en'));
  }

  @override
  bool shouldReload(_FallbackCupertinoLocalizationsDelegate old) => false;
}
